#!/bin/sh

# Delete Python's compiled *.pyc and __pycache__ files recursively in the current directory

if [ "$1" ]; then
    WHERE="$1"
else
    WHERE="$PWD"
fi

find "$WHERE" \
    -name '__pycache__' -delete -print \
    -o \
    -name '*.pyc' -delete -print
