# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainUI(object):
    def setupUi(self, MainUI):
        MainUI.setObjectName("MainUI")
        MainUI.resize(240, 450)
        MainUI.setMinimumSize(QtCore.QSize(240, 450))
        MainUI.setMaximumSize(QtCore.QSize(240, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/RustDaVinci-icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainUI.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainUI)
        self.centralwidget.setObjectName("centralwidget")
        self.load_image_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.load_image_PushButton.setGeometry(QtCore.QRect(10, 10, 220, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.load_image_PushButton.setFont(font)
        self.load_image_PushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.load_image_PushButton.setAcceptDrops(False)
        self.load_image_PushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.load_image_PushButton.setAutoFillBackground(False)
        self.load_image_PushButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/load_image_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_image_PushButton.setIcon(icon1)
        self.load_image_PushButton.setIconSize(QtCore.QSize(220, 45))
        self.load_image_PushButton.setCheckable(False)
        self.load_image_PushButton.setAutoDefault(False)
        self.load_image_PushButton.setDefault(False)
        self.load_image_PushButton.setFlat(True)
        self.load_image_PushButton.setObjectName("load_image_PushButton")
        self.identify_ctrl_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.identify_ctrl_PushButton.setGeometry(QtCore.QRect(10, 60, 220, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.identify_ctrl_PushButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/select_area_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.identify_ctrl_PushButton.setIcon(icon2)
        self.identify_ctrl_PushButton.setIconSize(QtCore.QSize(220, 45))
        self.identify_ctrl_PushButton.setFlat(True)
        self.identify_ctrl_PushButton.setObjectName("identify_ctrl_PushButton")
        self.paint_image_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.paint_image_PushButton.setEnabled(False)
        self.paint_image_PushButton.setGeometry(QtCore.QRect(10, 110, 220, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.paint_image_PushButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/paint_image_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.paint_image_PushButton.setIcon(icon3)
        self.paint_image_PushButton.setIconSize(QtCore.QSize(220, 45))
        self.paint_image_PushButton.setFlat(True)
        self.paint_image_PushButton.setObjectName("paint_image_PushButton")
        self.settings_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.settings_PushButton.setGeometry(QtCore.QRect(10, 160, 220, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.settings_PushButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/settings_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_PushButton.setIcon(icon4)
        self.settings_PushButton.setIconSize(QtCore.QSize(220, 45))
        self.settings_PushButton.setFlat(True)
        self.settings_PushButton.setObjectName("settings_PushButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(17, 220, 201, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.preview_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.preview_PushButton.setEnabled(False)
        self.preview_PushButton.setGeometry(QtCore.QRect(10, 350, 221, 41))
        self.preview_PushButton.setObjectName("preview_PushButton")
        self.progress_ProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_ProgressBar.setGeometry(QtCore.QRect(10, 400, 221, 21))
        self.progress_ProgressBar.setProperty("value", 0)
        self.progress_ProgressBar.setTextVisible(False)
        self.progress_ProgressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progress_ProgressBar.setInvertedAppearance(False)
        self.progress_ProgressBar.setObjectName("progress_ProgressBar")
        self.log_TextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.log_TextEdit.setGeometry(QtCore.QRect(10, 240, 221, 101))
        self.log_TextEdit.setUndoRedoEnabled(False)
        self.log_TextEdit.setReadOnly(True)
        self.log_TextEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.log_TextEdit.setObjectName("log_TextEdit")
        MainUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainUI)
        self.statusbar.setObjectName("statusbar")
        MainUI.setStatusBar(self.statusbar)

        self.retranslateUi(MainUI)
        QtCore.QMetaObject.connectSlotsByName(MainUI)

    def retranslateUi(self, MainUI):
        _translate = QtCore.QCoreApplication.translate
        MainUI.setWindowTitle(_translate("MainUI", "RustDaVinci"))
        self.load_image_PushButton.setText(_translate("MainUI", "         Load Image...        "))
        self.identify_ctrl_PushButton.setText(_translate("MainUI", " Capture Control Area..."))
        self.paint_image_PushButton.setText(_translate("MainUI", "         Paint Image           "))
        self.settings_PushButton.setText(_translate("MainUI", "            Settings              "))
        self.preview_PushButton.setText(_translate("MainUI", "Show Image >>"))
import ui.resources.icons_rc
